flanksource/mission-control-chart

chart/files/kratos-config.yaml
chart/values.yaml

Fixes: https://github.com/flanksource/incident-commander/issues/215

feat: session lifespan

---

chart/templates/deployment.yaml
chart/templates/postgrest.yaml
chart/templates/secrets.yaml
chart/values.yaml

Will be merged after duty PR: flanksource/duty#10 is merged and incident commander is updated to use new duty version

feat: add jwt secret and anon role to chart

---

chart/templates/deployment.yaml
chart/templates/postgrest.yaml
chart/templates/secrets.yaml
chart/values.yaml

fix: secret object problems

---

chart/templates/deployment.yaml

Merge this after https://github.com/flanksource/incident-commander/pull/272 is merged

feat: add health check endpoint

---

chart/templates/mission-control.yaml

feat: add mission-control system template

---

chart/templates/mission-control-configs.yaml
chart/templates/mission-control.yaml

chore: mission control topology updates

---

topologies/flux.yaml

Fixes: https://github.com/flanksource/mission-control-chart/issues/83

chore: add git repo to flux topology

---

topologies/connection.yaml
topologies/mission-control.yaml

Fixes: https://github.com/flanksource/mission-control-chart/issues/85

feat: use connection crd for mission control topology

---

topologies/flux.yaml

feat: link flux resources with config

---

chart/Chart.yaml
chart/templates/deployment.yaml
chart/values.yaml

Fixes: https://github.com/flanksource/mission-control-chart/issues/110

chore: add otel url and option to disable apm-hub

---

chart/templates/deployment.yaml
chart/templates/postgrest.yaml
chart/values.yaml

https://github.com/flanksource/duty/issues/286

feat: add limit to max rows on postgREST

---

.github/workflows/release.yml
Makefile
agent-chart/.helmignore
agent-chart/Chart.yaml
agent-chart/templates/_helpers.tpl
agent-chart/templates/required.yaml
agent-chart/templates/secret.yaml
agent-chart/values.yaml

feat: agent-chart

---

topologies/prometheus.yaml

Fixes: https://github.com/flanksource/canary-checker/issues/722

feat: add prometheus topology

---

chart/templates/postgres.yaml
chart/values.yaml

Merge https://github.com/flanksource/aws-sandbox/pull/206 before merging this PR

chore: add system id var for pganalyze

---

agent-chart/values.yaml

resolves: https://github.com/flanksource/mission-control-chart/issues/146

fix: agent chart storage class default

---

.github/workflows/release.yml

feat: do not create release if chart has beta dependencies

---

agent-chart/templates/deployment.yaml
agent-chart/values.yaml
chart/templates/deployment.yaml
chart/values.yaml

Depends on:  https://github.com/flanksource/canary-checker/pull/1851 & https://github.com/flanksource/config-db/pull/563/
Fixes: #175

chore: set default log level to info & enable json logs

---

chart/templates/rbac.yaml
chart/values.yaml

* Add mission-control-reader & mission-control-writer roles & bindings

feat: add impersonate permissin to mission-control role

---

.github/workflows/test.yml
agent-chart/Chart.yaml
agent-chart/templates/postgres-secret.yaml

Reason for empty topology push

chore: add DATABASE key in postgres secret

---

.prettierrc
chart/templates/servicemonitor.yaml
chart/values.yaml

resolves: https://github.com/flanksource/mission-control-chart/issues/211

feat: enable service monitors

---

chart/values.schema.json
chart/values.yaml

fix: schema changes for properties and labels

---

chart/values.schema.json
chart/values.yaml

Fixes: https://github.com/flanksource/mission-control-chart/issues/225

fix: change schema for annotations

---

chart/files/scrape-dashboard.json
chart/templates/scrape-dashboard-configmap.yaml
chart/values.schema.json
chart/values.yaml

feat; add scrape metrics grafana dashboard
